rootProject.ext.namespace = 'renetik.android.midi.bluetooth'
if (!rootProject.ext.is_renetik_development) apply from: '../library.gradle'
else apply from: '../../library.gradle'
dependencies {
    implementation project(':renetik-android-core')
    implementation project(':renetik-android-event')
    implementation project(':renetik-android-ui')
    implementation project(':renetik-android-store')
    api 'jp.kshoji:javax-sound-midi:0.0.6:@aar'
    api 'androidx.annotation:annotation:1.10.0'
    api fileTree(dir: 'libs', include: ['*.jar'])
}
repositories {
    maven {
        url = 'https://github.com/kshoji/javax.sound.midi-for-Android/raw/develop/javax.sound.midi/repository'
    }
    mavenCentral()
}